#!/usr/bin/env php
<?php

use herbie\Application;
use herbie\ApplicationPaths;

// create app paths
if (getenv('HERBIE_ENV') === 'dev') {
    require __DIR__ . '/vendor/autoload.php';
    $appPaths = new ApplicationPaths(
        __DIR__,
        __DIR__ . '/vendor',
        __DIR__ . '/website/site',
        __DIR__ . '/website/web'
    );
} else {
    require dirname(__DIR__, 3) . '/vendor/autoload.php';
    $appPaths = new ApplicationPaths(
        dirname(__DIR__, 3),
        dirname(__DIR__, 3) . '/site',
        dirname(__DIR__, 3) . '/vendor',
        dirname(__DIR__, 3) . '/web'
    );
}

// create app
$app = new Application(
    $appPaths,
);

$app->runCli();
