#!/usr/bin/env php
<?php

use herbie\Application;
use herbie\ApplicationPaths;

// create app paths
if (getenv('HERBIE_ENV') === 'dev') {
    require __DIR__ . '/vendor/autoload.php';
    $appPaths = new ApplicationPaths(
        __DIR__,
        __DIR__ . '/example/site',
    );
} else {
    require dirname(__DIR__, 2) . '/vendor/autoload.php';
    $appPaths = new ApplicationPaths(
        dirname(__DIR__, 2),
        dirname(__DIR__, 2) . '/example/site',
        dirname(__DIR__, 2) . '/vendor'
    );
}

// create app
$app = new Application(
    $appPaths,
);

$app->runCli();
