show_raw_data: true
password: 88cceeb3a39d7f9172c228028e46cb69
layouts:
  default.html:
    segments:
      '': Inhalt
  blog.html:
    segments:
      '': Inhalt
  documentation.html:
    segments:
      '': Inhalt
  home.html:
    segments:
      '': Inhalt
      boxes: Boxen
      footer: Footer
fields:
  alias:
    label: Alias
    type: label
    group: Info
  path:
    label: Pfad
    type: label
    group: Info
  title:
    label: Titel
    type: text
    group: Allgemein
  layout:
    label: Layout
    type: pagelayout
    group: Layout
  date:
    label: Datum
    type: text
    placeholder: 'JJJJ-MM-DD'
    group: Allgemein
  format:
    label: Formatierung
    type: pageformat
    group: Layout
  excerpt:
    label: Zusammenfassung
    type: textarea
    group: Allgemein
  disabled:
    label: Seite deaktivieren
    type: checkbox
    group: Allgemein
  hidden:
    label: In Men체s ausblenden
    type: checkbox
    group: Allgemein
  nocache:
    label: Seitencache deaktivieren
    type: checkbox
    group: Allgemein
  keep_extension:
    label: Dateiendung behalten
    type: checkbox
    group: Layout
  content_type:
    label: Content-Type
    type: text
    group: Layout
  categories:
    label: Kategorien
    type: multitext
    group: Tags
  authors:
    label: Autoren
    type: multitext
    group: Tags
  tags:
    label: Tags
    type: multitext
    group: Tags
  category:
    label: Kategorie (veraltet)
    type: text
    group: Tags
  author:
    label: Author (veraltet)
    type: text
    group: Tags
  yaml:
    label: YAML-Test
    type: yaml
    group: YAML
  image:
    label: Bild
    type: mediaimage
    group: Media

data:
  commands:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
  events:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
      order:
        label: Sortierung
        type: text
        placeholder: Sortierung
  menu:
    config:
      route:
        label: Route
        type: text
        placeholder: Route
      label:
        label: Label
        type: text
        placeholder: Label
  page_extensions:
    config:
      extension:
        label: Erweiterung
        type: dropdownlist
        items:
          htm: HTM
          html: HTML
          markdown: Markdown
          md: Markdown (MD)
          rss: RSS
          rst: reStructuredText
          textile: Textile
          txt: Text
          xml: XML
      formatter: 
        label: Formatierer
        type: text
      conversion:
        label: Konvertierung
        type: dropdownlist
        items:
          No: Nein
          Yes: Ja                  
  plugins:
    config:
      id:
        label: ID
        type: text
      name:
        label: Name
        type: text
      text:
        label: Kurztext
        type: text
      author:
        label: Autor
        type: text
      version:
        label: Version
        type: text
      composer:
        label: Composer
        type: text
      packagist:
        label: Packagist
        type: text
  site_dir_basic:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
  site_dir_extended:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
  twig_filters:
    config:
      name:
        label: Name
        type: text
      code:
        label: Code
        type: text
      desc:
        label: Beschreibung
        type: text
      params:
        label: Parameter
        type: matrix
        config:
          name:
            type: text
          type:
            type: text
          desc:
            type: text
          default:
            type: text
      return:
        label: Return
        type: multitext
  twig_filters_builtin:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      slug:
        label: Slug
        type: text
        placeholder: Slug
  twig_functions:
    config:
      name:
        label: Name
        type: text
      code:
        label: Code
        type: text
      desc:
        label: Beschreibung
        type: text
      params:
        label: Parameter
        type: matrix
        config:
          name:
            type: text
          type:
            type: text
          desc:
            type: text
          default:
            type: text
      return:
        label: Return
        type: multitext
  twig_functions_builtin:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      slug:
        label: Slug
        type: text
        placeholder: Slug
  twig_tags_builtin:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      slug:
        label: Slug
        type: text
        placeholder: Slug
  twig_tests:
    config:
      name:
        label: Name
        type: text
      code:
        label: Code
        type: text
      desc:
        label: Beschreibung
        type: text
      return:
        label: Return
        type: multitext
        hint: 'Das ist eine Erk채rung zum oberen Feld'
  twig_tests_builtin:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      slug:
        label: Slug
        type: text
        placeholder: Slug        
  vars_content:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
  vars_global:
    config:
      name:
        label: Name
        type: text
        placeholder: Name
      desc:
        label: Beschreibung
        type: text
        placeholder: Beschreibung
  vars_page:
    config:
      name:
        label: Name
        type: text
      desc:
        label: Beschreibung
        type: text
  vars_site:
    config:
      name:
        label: Name
        type: text
      desc:
        label: Beschreibung
        type: text        
  _test:
    config:
      name:
        label: Name
        type: text
      textarea:
        label: Textarea
        type: textarea
      return:
        label: Argumente
        type: multitext
        hint: 'Das ist eine Erk채rung zum oberen Feld'
      hidden:
        label: Versteckt
        type: checkbox
      radiolist:
        label: Radiolist
        type: radiolist
        items:
          A: B
          C: D
          E: F
          G: H
          I: J
      checkboxlist:
        label: Checkboxlist
        type: checkboxlist
        items:
          A: B
          C: D
          E: F
          G: H
          I: J
      select:
        label: Select
        type: dropdownlist
        items:
          '': 'Bitte w채hlen'
          A: B
          C: D
          E: F
          G: H
          I: J
      param:
        label: Parameter
        type: multitext
      matrix:
        label: Matrix
        type: matrix
        config:
          text1:
            type: text
            placeholder: 'Text 1'
          text2:
            type: text
            placeholder: 'Text 2'
          text3:
            type: text
            placeholder: 'Text 3'
